# Generated by Django 5.0.1 on 2025-05-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_stripe_payment_intent_alter_order_user_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_products', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Analytics',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='api_user_role_9b9076_idx'),
        ),
        migrations.AddIndex(
            model_name='analytics',
            index=models.Index(fields=['date'], name='api_analyti_date_dbedc7_idx'),
        ),
    ]
